apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api-main
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: { { .Values.spec.destination.namespace } }
    server: { { .Values.spec.destination.server } }
  project: { { .Values.spec.project } }
  source:
    path: kustomize/gateway-api/overlays/main
    repoURL: { { .Values.spec.source.repoURL } }
    targetRevision: { { .Values.spec.source.targetRevision } }
  syncPolicy:
    automated: {}
