apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api
spec:
  template:
    spec:
      serviceAccountName: secret-manager-sa
      containers:
        - name: gateway-api
          # just a placeholder for kustomize
          image: gateway-api
          volumeMounts:
            - name: gateway-api-secrets-main
              mountPath: /app/.env
              readOnly: true
              subPath: .env
      volumes:
        - name: gateway-api-secrets-main
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: gateway-api-secrets-main
