apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - secret.yaml

commonLabels:
  app: gateway-api-main

nameSuffix: -main

patches:
  - path: deployment.yaml
    target:
      kind: Deployment
      name: gateway-api

images:
  - name: gateway-api
    newName: ghcr.io/saenyakorn/simple-services/gateway-api
    newTag: 1.0.0
