apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: gateway-api-secrets
spec:
  provider: aws
  secretObjects:
    - secretName: gateway-api-secrets
      type: Opaque
  parameters:
    objects: |
      - objectName: main/gateway-api
        objectType: secretsmanager
        objectAlias: .env
