apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: simple-services
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Example for simple services
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
